"""
Workdir layout resolver — single source of truth for all output paths.

The pipeline never writes to the source tree. All generated artifacts and
mutable state live under a per-build *workdir* supplied at runtime via
``--workdir`` or the ``paths.workdir`` config key.

Workdir layout::

    <workdir>/
      results/
        ingest/
          pathoplexus_metadata.tsv
          pathoplexus_sequences.fasta
          merged_metadata.tsv
          merged_sequences.fasta
          final_metadata.tsv
          final_sequences.fasta
        subsampled/
          metadata.tsv
          sequences.fasta
        alignments/
          aligned.fasta
          masked.fasta
        trees/
          tree.nwk
        refine/
          timetree.nwk
          branch_lengths.json
        node_data/
          nt_muts.json
          aa_muts.json
          traits.json
          clades.json
      auspice/
        results.json
      cache/
        cache_coordinates.tsv     # writable copy; seeded from build config on first run
      config/
        latlongs.tsv              # generated by coordinates step
        colour_scheme.tsv         # generated by colours step
        name2hue.tsv              # generated by generate_name2hue step
        backbone_strains.txt      # optional; written by flexpipe-run --backbone-from
      logs/
        ingest.log
        phylo.log
      manifest.json
"""

import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Union

logger = logging.getLogger(__name__)


@dataclass
class WorkdirPaths:
    """All output file paths derived from a single *root* workdir.

    Instantiate with ``WorkdirPaths.from_root("/path/to/workdir")``.  All
    attributes are ``pathlib.Path`` objects; parent directories are created
    lazily when ``ensure_dirs()`` is called.
    """

    root: Path

    # ── ingest outputs ──────────────────────────────────────────────────────
    @property
    def results(self) -> Path:
        return self.root / "results"

    @property
    def ingest_dir(self) -> Path:
        return self.results / "ingest"

    @property
    def subsampled_dir(self) -> Path:
        return self.results / "subsampled"

    @property
    def subsampled_metadata(self) -> Path:
        return self.subsampled_dir / "metadata.tsv"

    @property
    def subsampled_sequences(self) -> Path:
        return self.subsampled_dir / "sequences.fasta"

    # ── phylogenetic outputs ─────────────────────────────────────────────────
    @property
    def alignments_dir(self) -> Path:
        return self.results / "alignments"

    @property
    def trees_dir(self) -> Path:
        return self.results / "trees"

    @property
    def auspice_dir(self) -> Path:
        return self.root / "auspice"

    @property
    def auspice_json(self) -> Path:
        return self.auspice_dir / "results.json"

    # ── generated config artifacts ───────────────────────────────────────────
    @property
    def generated_config_dir(self) -> Path:
        return self.root / "config"

    @property
    def latlongs(self) -> Path:
        return self.generated_config_dir / "latlongs.tsv"

    @property
    def colour_scheme(self) -> Path:
        return self.generated_config_dir / "colour_scheme.tsv"

    @property
    def name2hue(self) -> Path:
        return self.generated_config_dir / "name2hue.tsv"

    @property
    def snakemake_config_overrides(self) -> Path:
        return self.generated_config_dir / "snakemake_resolved.yaml"

    @property
    def subsample_config_resolved(self) -> Path:
        """Workdir-local subsample config with ``defaults.max_date`` injected from run_date."""
        return self.generated_config_dir / "subsample_resolved.yaml"

    @property
    def backbone_strains(self) -> Path:
        """One-strain-per-line include-list materialized from a previous run's subsampled metadata.

        Written by ``flexpipe-run --backbone-from`` before Snakemake is invoked; referenced as a
        synthetic ``samples.__backbone__.include`` entry in the resolved subsample config so
        ``augur subsample`` force-keeps the listed strains regardless of group caps.
        The parent ``config/`` directory is created by :meth:`ensure_dirs`.
        """
        return self.generated_config_dir / "backbone_strains.txt"

    # ── mutable cache ────────────────────────────────────────────────────────
    @property
    def cache_dir(self) -> Path:
        return self.root / "cache"

    @property
    def cache_coordinates(self) -> Path:
        return self.cache_dir / "cache_coordinates.tsv"

    @property
    def cache_name2hue(self) -> Path:
        return self.cache_dir / "name2hue.tsv"

    # ── logs ─────────────────────────────────────────────────────────────────
    @property
    def logs_dir(self) -> Path:
        return self.root / "logs"

    @property
    def ingest_log(self) -> Path:
        return self.logs_dir / "ingest.log"

    @property
    def phylo_log(self) -> Path:
        return self.logs_dir / "phylo.log"

    # ── QC artifacts ─────────────────────────────────────────────────────────
    @property
    def filter_log(self) -> Path:
        """Per-strain filter log written by ``augur filter --output-log``."""
        return self.ingest_dir / "filter_log.tsv"

    @property
    def qc_report(self) -> Path:
        """Structured JSON QC report written by ``flexpipe-qc-summary``."""
        return self.results / "qc_report.json"

    @property
    def qc_summary(self) -> Path:
        """Flat TSV QC summary (per-grade counts) written by ``flexpipe-qc-summary``."""
        return self.results / "qc_summary.tsv"

    # ── concurrency ───────────────────────────────────────────────────────────
    @property
    def lock_file(self) -> Path:
        """Workdir-level lock file used by ``filelock`` to prevent concurrent runs."""
        return self.root / ".flexpipe.lock"

    # ── provenance ───────────────────────────────────────────────────────────
    @property
    def manifest(self) -> Path:
        return self.root / "manifest.json"

    # ── helpers ──────────────────────────────────────────────────────────────

    def ensure_dirs(self) -> None:
        """Create all output directories (idempotent)."""
        dirs = [
            self.ingest_dir,
            self.subsampled_dir,
            self.alignments_dir,
            self.trees_dir,
            self.auspice_dir,
            self.generated_config_dir,
            self.cache_dir,
            self.logs_dir,
        ]
        for d in dirs:
            d.mkdir(parents=True, exist_ok=True)
        logger.debug("Ensured workdir layout under %s", self.root)

    @classmethod
    def from_root(cls, root: Union[str, Path]) -> "WorkdirPaths":
        """Create a ``WorkdirPaths`` from a root directory path."""
        return cls(root=Path(root).resolve())
