name: nextstrain

channels:
- conda-forge
- bioconda
- defaults

dependencies:
- augur>=13
- nextalign
- nextstrain-cli
- python>=3.9
- nodejs>=10
- git
- pip
- iqtree
- mafft
- beautifulsoup4
- geopy
- tabulate
- snakemake-minimal
- unidecode

- pip:
  - pycountry-convert
  - pycountry
  - xlrd
  - lxml
  - openpyxl
  - matplotlib>=3.9
  - colour
